[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/COMPANY_NAME/documentserver/nginx/out.log
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/COMPANY_NAME/documentserver/nginx/err.log
stderr_logfile_backups=0
stderr_logfile_maxbytes=0
