[unix_http_server]
file=/tmp/supervisord.sock

[supervisord]
nodaemon=false
pidfile=/tmp/supervisord.pid
logfile=/tmp/log/supervisor/supervisord.log
childlogdir=/tmp/log/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisord.sock

[include]
files = /etc/supervisor/conf.d/*.conf
